/* Extracts the offline AIController from the client and emits it as a server module.
   The class is written verbatim inside a factory so the free identifiers it relies on
   (dist, clamp, AB, BALANCE, ...) resolve to injected parameters instead of client
   globals. Regenerate whenever the client AI changes, exactly like the catalogue, so
   the offline and online opponents cannot drift apart. */
import { createHash } from 'node:crypto';
import { mkdir, readFile, writeFile } from 'node:fs/promises';

const NL = String.fromCharCode(10);
const sourcePath = new URL('../apps/client/src/game-runtime.js', import.meta.url);
const outPath = new URL('../packages/server-core/generated/ai-controller.generated.js', import.meta.url);
const source = await readFile(sourcePath, 'utf8');
const lines = source.split(NL);

const start = source.indexOf('class AIController {');
const end = source.indexOf('class AudioManager', start);
if (start < 0 || end < 0) throw new Error('Could not locate AIController in the client runtime');
const body = source.slice(start, end).trimEnd();
if (!body.endsWith('}')) throw new Error('AIController extraction did not end on a closing brace');

/* The AI also leans on a handful of Game methods for threat assessment. Those are
   extracted verbatim too. Everything else it touches - casting, VFX, logging - is
   bridged to the server simulation by the host rather than ported. */
const HELPER_METHODS = [
  'isInCombat', 'breakableControl', 'abilityReady', 'majorDefensiveActive',
  'unitUnderMajorOffensive', 'majorOffensiveActiveOnUnit', 'unitUnderBurst', 'botCanSelfSaveSoon',
  'teamOffensiveWindowFor', 'tryBotControlledDefensive', 'tryBotEmergencyDefensive',
  'shouldBotTrinket', 'botTrinketDelay'
];

function extractMethod(name) {
  /* Methods sit at one or two spaces of indent inside the Game class. Matched by string
     prefix rather than regex so the generator stays free of escaping hazards. */
  const heads = [' ' + name + '(', '  ' + name + '('];
  const aiStart = lines.findIndex(l => l.startsWith('class AIController'));
  const aiEnd = lines.findIndex((l, i) => i > aiStart && l.startsWith('class AudioManager'));
  for (let i = 0; i < lines.length; i++) {
    if (!heads.some(h => lines[i].startsWith(h))) continue;
    if (i > aiStart && i < aiEnd) {
      throw new Error(name + ' is an AIController method, not a Game method; it must not be lifted onto the host');
    }
    let depth = 0;
    const out = [];
    for (let j = i; j < lines.length; j++) {
      out.push(lines[j]);
      for (const ch of lines[j]) {
        if (ch === '{') depth++;
        else if (ch === '}') depth--;
      }
      if (depth <= 0) break;
    }
    return out.join(NL);
  }
  throw new Error('Could not extract Game method ' + name);
}
const helpers = HELPER_METHODS.map(extractMethod).join(NL);

/* The AI casts by index into AB[cls], and the client builds that array by walking
   TALENT_UNLOCKED_ABILITIES in key order. That order is not alphabetical and does not
   match the catalogue, so it has to be captured verbatim or every talent ability ends
   up at the wrong index. */
const vm = await import('node:vm');
function slice(from, to) { return source.slice(source.indexOf(from), source.indexOf(to, source.indexOf(from))); }
const sandbox = { Object, Set };
vm.createContext(sandbox);
vm.runInContext([
  slice('const COLORS=', 'const BALANCE='),
  slice('const AB=', 'const SUPPORTED_TALENT_ABILITY_TYPES='),
  'globalThis.__extract = { AB, TALENT_UNLOCKED_ABILITIES };'
].join(NL), sandbox, { timeout: 2000 });
const { AB, TALENT_UNLOCKED_ABILITIES } = sandbox.__extract;
const talentOrder = {};
for (const cls of Object.keys(TALENT_UNLOCKED_ABILITIES)) {
  talentOrder[cls] = Object.entries(TALENT_UNLOCKED_ABILITIES[cls])
    .filter(([, ability]) => ability.type !== 'passiveOnly')
    .map(([talentId]) => talentId);
}
const baseOrder = {};
for (const cls of Object.keys(AB)) baseOrder[cls] = AB[cls].map(a => a.name);

const digest = createHash('sha256').update(source).digest('hex');
const deps = ['dist', 'clamp', 'isUntargetableStealth', 'windTigereyeStacks', 'bracketKey', 'classRating', 'AB', 'BALANCE', 'DIFFICULTY', 'CLASS_INFO', 'talentRank', 'unitTalentRank'];

await mkdir(new URL('../packages/server-core/generated/', import.meta.url), { recursive: true });
await writeFile(outPath, [
  '/* GENERATED by scripts/generate-ai.mjs. Do not edit by hand. */',
  '/* Extracted from apps/client/src/game-runtime.js (sha256 ' + digest + ') */',
  'export const aiSourceDigest = ' + JSON.stringify(digest) + ';',
  '',
  '/* Client AB[cls] layout: base ability names in order, then the talent ids appended',
  '   by syncTalentUnlockedAbilities. The AI addresses abilities by index into this. */',
  'export const CLIENT_BASE_ORDER = ' + JSON.stringify(baseOrder, null, 2) + ';',
  'export const CLIENT_TALENT_ORDER = ' + JSON.stringify(talentOrder, null, 2) + ';',
  '',
  'export function createAIControllerClass({ ' + deps.join(', ') + ' }) {',
  body,
  '  return AIController;',
  '}',
  '',
  '/* Threat-assessment helpers lifted from the client Game class, mixed onto the host so',
  '   the ported AI evaluates danger exactly as it does offline. */',
  'export function createGameHelpers({ ' + deps.join(', ') + ' }) {',
  '  return class AiGameHelpers {',
  helpers,
  '  };',
  '}',
  ''
].join(NL));

console.log('Extracted AIController: ' + body.length + ' chars.');
console.log('Extracted ' + HELPER_METHODS.length + ' Game helper methods: ' + helpers.length + ' chars.');
