window.AETHER_ABILITY_ART = {
  "Cinder Bolt": "FireMage/FireMage_2",
  "Ember Lance": "FireMage/FireMage_20",
  "Frostfire Nova": "FireMage/FireMage_34",
  "Blazing Step": "FireMage/FireMage_33",
  "Prism Hex": "FireMage/FireMage_24",
  "Counterflare": "FireMage/FireMage_22",
  "Ice Block": "FireMage/FireMage_32",
  "Meteor": "FireMage/FireMage_16",
  "Cauterize": "FireMage/FireMage_10",
  "Combustion": "FireMage/FireMage_26",
  "Dragon Breath": "FireMage/FireMage_29",
  "Living Bomb": "FireMage/FireMage_3",
  "Fire Shield": "FireMage/FireMage_21",
  "Alter Time": "FireMage/FireMage_36",
  "Meteor Spear": "FireMage/FireMage_3",
  "Molten Armor": "FireMage/FireMage_21",

  "Night Slash": "Hunter/Hunter_11",
  "Umbral Pounce": "Hunter/Hunter_7",
  "Viper Cut": "Hunter/Hunter_13",
  "Smoke Veil": "Hunter/Hunter_19",
  "Blind": "Hunter/Hunter_6",
  "Ribbreaker": "Hunter/Hunter_22",
  "Shadow Kick": "Engineer/Engineer_2",
  "Cloak of Shadows": "Hunter/Hunter_21",
  "Evasion": "Hunter/Hunter_3",
  "Garrote": "Hunter/Hunter_17",
  "Gouge": "Hunter/Hunter_16",
  "Crimson Vial": "Hunter/Hunter_25",
  "Vendetta": "Hunter/Hunter_18",
  "Shiv": "Hunter/Hunter_15",
  "Sap": "Hunter/Hunter_4",

  "Arc Spark": "Monk/Monk_31",
  "Forked Current": "Monk/Monk_32",
  "Skybreaker Pulse": "Monk/Monk_30",
  "Static Aegis": "Engineer/Engineer_12",
  "Gale Reversal": "Monk/Monk_40",
  "Static Snare": "Monk/Monk_33",
  "Wind Shear": "Monk/Monk_34",
  "Flame Shock": "FireMage/FireMage_5",
  "Chain Spark": "Engineer/Engineer_20",
  "Healing Surge": "Engineer/Engineer_20",
  "Frost Shock": "Engineer/Engineer_24",
  "Lava Burst": "FireMage/FireMage_25",
  "Volcanic Eruption": "FireMage/FireMage_25",
  "Totem Mastery": "Druid/Druid_23",
  "Static Field": "Monk/Monk_35",
  "Stormkeeper": "Engineer/Engineer_16",
  "Grounding Aegis": "Engineer/Engineer_13",
  "Thunderstep": "Engineer/Engineer_19",
  "Mana Well": "Druid/Druid_23",

  "Zephyr Palm": "Monk/Monk_28",
  "Cloudstep Kick": "Monk/Monk_37",
  "Fists of Fury": "Monk/Monk_26",
  "Disrupting Palm": "Monk/Monk_5",
  "Valley Sweep": "Monk/Monk_23",
  "Willow Guard": "Monk/Monk_18",
  "Incapacitate": "Monk/Monk_16",
  "Cyclone Barrage": "Monk/Monk_24",
  "Touch of Death": "Necromancer/Necromancer_23",
  "Whirling Dragon Punch": "Monk/Monk_12",
  "Disabling Reach": "Monk/Monk_36",
  "Touch of Karma": "Monk/Monk_25",
  "Strike of the Windlord": "Monk/Monk_38",
  "Tigereye Brew": "Monk/Monk_20",
  "Tiger's Lust": "Druid/Druid_25",
  "Tiger Rush": "Druid/Druid_24",

  "Soul Scar": "Necromancer/Necromancer_1",
  "Creeping Torment": "Necromancer/Necromancer_3",
  "Unstable Affliction": "Necromancer/Necromancer_17",
  "Essence Siphon": "Necromancer/Necromancer_20",
  "Grasping Gloom": "Necromancer/Necromancer_18",
  "Soul Barrier": "Necromancer/Necromancer_11",
  "Fear": "Necromancer/Necromancer_9",
  "Dark Pact": "Necromancer/Necromancer_10",
  "Mortal Horror": "Necromancer/Necromancer_16",
  "Pandemic Bloom": "Necromancer/Necromancer_2",
  "Shadowfury": "Necromancer/Necromancer_14",
  "Undying Resolve": "Necromancer/Necromancer_12",
  "Void Mend": "Necromancer/Necromancer_6",

  "Verdant Mend": "Druid/Druid_5",
  "Blooming Echo": "Druid/Druid_6",
  "Spirit Blossom": "Druid/Druid_13",
  "Renewal Tide": "Druid/Druid_20",
  "Purifying Light": "Druid/Druid_9",
  "Fae Retreat": "Druid/Druid_2",
  "Lullaby Bloom": "Druid/Druid_12",
  "G'Hanir, the Mother Tree": "Druid/Druid_22",
  "Nature’s Grasp": "Druid/Druid_18",
  "Rejuvenate": "Druid/Druid_7",
  "Nature Swiftness": "Druid/Druid_1",
  "Ironbark": "Druid/Druid_16",

  "Holy Light": "Monk/Monk_2",
  "Holy Shock": "Monk/Monk_15",
  "Blessing of Sacrifice": "Monk/Monk_14",
  "Bestow Faith": "Monk/Monk_29",
  "Divine Protection": "Monk/Monk_10",
  "Hammer of Justice": "Engineer/Engineer_1",
  "Divine Steed": "Hunter/Hunter_1",
  "Cleanse": "Monk/Monk_3",
  "Blinding Light": "Monk/Monk_13",
  "Divine Toll": "Monk/Monk_27",
  "Blessing of Freedom": "Monk/Monk_1",
  "Guardian Angel": "Monk/Monk_21",
  "Judgement": "Monk/Monk_17",
  "Word of Glory": "Monk/Monk_8",
  "Avenging Wings": "Monk/Monk_11",

  "Smite": "Monk/Monk_4",
  "Power Shield": "Monk/Monk_6",
  "Penance": "Monk/Monk_7",
  "Shadow Mend": "Necromancer/Necromancer_21",
  "Solace": "FireMage/FireMage_27",
  "Pain Suppression": "Monk/Monk_9",
  "Ultimate Radiance": "FireMage/FireMage_40",
  "Purify": "Monk/Monk_22",
  "Psychic Scream": "Necromancer/Necromancer_25",
  "Fade": "Monk/Monk_19",
  "Angelic Body": "FireMage/FireMage_37",
  "Archangel": "Druid/Druid_15",
  "Dark Archangel": "Necromancer/Necromancer_7",

  "Mortal Swing": "EarthMage/EarthMage_6",
  "Charge": "EarthMage/EarthMage_20",
  "Rend": "Hunter/Hunter_12",
  "Pummel": "Engineer/Engineer_5",
  "Spell Reflection": "EarthMage/EarthMage_16",
  "Intimidating Shout": "Hunter/Hunter_9",
  "Shield Wall": "EarthMage/EarthMage_39",
  "Battle Banner": "Engineer/Engineer_10",
  "Warbreaker": "EarthMage/EarthMage_3",
  "Execute Strike": "EarthMage/EarthMage_33",
  "Stormbolt": "Engineer/Engineer_17",
  "Bladestorm": "Engineer/Engineer_4",
  "Rallying Wall": "EarthMage/EarthMage_40",
  "Avatar": "EarthMage/EarthMage_28",
  "Victory Rush": "Engineer/Engineer_23",

  "Hot Streak": "FireMage/FireMage_13",
  "Meteor Lance": "FireMage/FireMage_18",
  "Rising Sun Kick": "Monk/Monk_39",
  "Instant Lava Burst": "FireMage/FireMage_25",
  "Radiant Penance": "Monk/Monk_7",
  "Instant Lullaby Bloom": "Druid/Druid_12",
  "Swift Renewal Tide": "Druid/Druid_20",
  "Cloudstep Dash": "Monk/Monk_37",
  "Free Arc Spark": "Monk/Monk_31",
  "Tempest Bolt": "Monk/Monk_39",
  "Eviscerate": "Hunter/Hunter_24",
  "Empowered Mortal Swing": "EarthMage/EarthMage_6",
  "Warbreaker Swing": "EarthMage/EarthMage_3",
  "Gushing Wound": "Hunter/Hunter_17"
};

window.AETHER_TALENT_PACKS = {
  flame: ["FireMage/FireMage_5","FireMage/FireMage_10","FireMage/FireMage_13","FireMage/FireMage_18","FireMage/FireMage_21","FireMage/FireMage_26","FireMage/FireMage_29","FireMage/FireMage_36","FireMage/FireMage_37","FireMage/FireMage_40"],
  shadow: ["Hunter/Hunter_2","Hunter/Hunter_3","Hunter/Hunter_4","Hunter/Hunter_9","Hunter/Hunter_14","Hunter/Hunter_15","Hunter/Hunter_17","Hunter/Hunter_18","Hunter/Hunter_21","Hunter/Hunter_24"],
  storm: ["Engineer/Engineer_2","Engineer/Engineer_10","Engineer/Engineer_12","Engineer/Engineer_13","Engineer/Engineer_16","Engineer/Engineer_19","Engineer/Engineer_20","Engineer/Engineer_23","Engineer/Engineer_24"],
  wind: ["Monk/Monk_1","Monk/Monk_6","Monk/Monk_8","Monk/Monk_11","Monk/Monk_12","Monk/Monk_17","Monk/Monk_20","Monk/Monk_25","Monk/Monk_36","Monk/Monk_38","Monk/Monk_39"],
  soul: ["Necromancer/Necromancer_2","Necromancer/Necromancer_6","Necromancer/Necromancer_7","Necromancer/Necromancer_10","Necromancer/Necromancer_11","Necromancer/Necromancer_12","Necromancer/Necromancer_14","Necromancer/Necromancer_16","Necromancer/Necromancer_22","Necromancer/Necromancer_25"],
  sage: ["Druid/Druid_1","Druid/Druid_2","Druid/Druid_7","Druid/Druid_10","Druid/Druid_15","Druid/Druid_16","Druid/Druid_18","Druid/Druid_22","Druid/Druid_24","Druid/Druid_25"],
  pala: ["Monk/Monk_1","Monk/Monk_3","Monk/Monk_8","Monk/Monk_13","Monk/Monk_14","Monk/Monk_17","Monk/Monk_21","Monk/Monk_27","Monk/Monk_29"],
  disc: ["Monk/Monk_4","Monk/Monk_6","Monk/Monk_7","Monk/Monk_9","Monk/Monk_19","Monk/Monk_22","FireMage/FireMage_37","FireMage/FireMage_40","Necromancer/Necromancer_7"],
  warrior: ["EarthMage/EarthMage_3","EarthMage/EarthMage_6","EarthMage/EarthMage_15","EarthMage/EarthMage_16","EarthMage/EarthMage_28","EarthMage/EarthMage_33","EarthMage/EarthMage_39","EarthMage/EarthMage_40","Engineer/Engineer_4","Engineer/Engineer_5","Engineer/Engineer_10","Engineer/Engineer_17"]
};
